language: node_js
node_js:
  - "stable"
notifications:
  email: false

cache:
  directories:
  - node_modules

script:
  npx cypress run

deploy:
  provider: pages
  skip_cleanup: true
  github-token: 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
  local_dir: build
  on:
    branch: master